### Site metadata ###

site_name: RMTechTransfer Blog
site_description: Random blog to track the randomness and curiosity, personal and professional.
site_url: https://rmtechtransfer/mkdocs-quickstart/

repo_url: https://github.com/okbobm/ideal-octo-fortnight
edit_uri: edit/master/docs/docs

### Build settings ###

theme: material

nav:
  - Home: index.md
  - AboutMe: 
      - About me: AboutMe/about-me.md
      - Resume: AboutMe/resume.md
  - Projects:
      - TL;DR: Projects/tldr.md
